name: Rust

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --all-features
    - name: Check
      run: cargo check --all-targets --verbose
    - name: Tests
      run: cargo test --verbose